51. Create a structured array representing a position (x, y) and a color (r, g, b)

In [1]:
import numpy as np

dtype = [('position', [('x', float), ('y', float)]), ('color', [('r', int), ('g', int), ('b', int)])]
array = np.zeros(5, dtype=dtype)
print(array)


[((0., 0.), (0, 0, 0)) ((0., 0.), (0, 0, 0)) ((0., 0.), (0, 0, 0))
 ((0., 0.), (0, 0, 0)) ((0., 0.), (0, 0, 0))]


52. Consider a random vector with shape (100,2) representing coordinates, find point-by-point distances

In [4]:
points = np.random.rand(100, 2)
distances = np.sqrt(((points[:, np.newaxis, :] - points[np.newaxis, :, :]) ** 2).sum(axis=-1))
print(distances)


[[0.         0.40021148 0.50565099 ... 0.44828846 0.32239858 0.42945272]
 [0.40021148 0.         0.78314957 ... 0.64475639 0.7224671  0.07412021]
 [0.50565099 0.78314957 0.         ... 0.17852871 0.43507303 0.76621236]
 ...
 [0.44828846 0.64475639 0.17852871 ... 0.         0.49954184 0.61713861]
 [0.32239858 0.7224671  0.43507303 ... 0.49954184 0.         0.74800472]
 [0.42945272 0.07412021 0.76621236 ... 0.61713861 0.74800472 0.        ]]


53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [5]:
arr = np.arange(10, dtype=np.float32)
arr = arr.astype(np.int32, copy=False)
print(arr)


[0 1 2 3 4 5 6 7 8 9]


54. How to read the following file?

In [ ]:
arr = np.genfromtxt('file.txt', delimiter=",", dtype=int)
print(arr)


[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


55. What is the equivalent of enumerate for NumPy arrays?

In [9]:
arr = np.array([10, 20, 30, 40])
for index, value in np.ndenumerate(arr):
    print(index, value)


(0,) 10
(1,) 20
(2,) 30
(3,) 40


56. Generate a generic 2D Gaussian-like array

In [10]:
X, Y = np.meshgrid(np.linspace(-1, 1, 10), np.linspace(-1, 1, 10))
D = np.sqrt(X*X + Y*Y)
sigma, mu = 1.0, 0.0
gaussian = np.exp(-( (D - mu)**2 / (2.0 * sigma**2) ))
print(gaussian)


[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

57. How to randomly place p elements in a 2D array?

In [11]:
n, p = 10, 5
arr = np.zeros((n, n))
indices = np.random.choice(n*n, p, replace=False)
arr.ravel()[indices] = 1
print(arr)


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


58. Subtract the mean of each row of a matrix


In [12]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1, keepdims=True)
print(Y)


[[-0.17619052  0.13872826  0.38181436  0.30938099  0.28309176 -0.12175796
  -0.41211653 -0.05086871 -0.02180692 -0.33027474]
 [ 0.41220281 -0.10026182  0.08363676  0.1916233  -0.47228137  0.14244077
   0.45939946 -0.29177551 -0.47281105  0.04782665]
 [-0.08787432 -0.22600941  0.10399573 -0.17478962 -0.06788182  0.12525057
   0.36550398 -0.23450844  0.12118937  0.07512397]
 [ 0.20815056 -0.03172298  0.11098353  0.21886719 -0.29878001  0.1352444
  -0.21934323 -0.0907051  -0.11502972  0.08233536]
 [-0.30277728 -0.30598991 -0.3258967   0.16098984  0.20439527  0.44303014
  -0.42739645  0.23517424  0.19068355  0.1277873 ]]


59. How to sort an array by the nth column?

In [13]:
arr = np.random.randint(0, 10, (5, 5))
sorted_arr = arr[arr[:, 2].argsort()]
print(sorted_arr)


[[8 2 1 1 8]
 [4 3 2 3 1]
 [5 3 3 9 3]
 [2 3 3 4 7]
 [2 2 6 5 4]]


60. How to tell if a given 2D array has null columns?

In [14]:
arr = np.array([[1, 0, 3], [4, 0, 6], [7, 0, 9]])
null_columns = np.all(arr == 0, axis=0)
print(null_columns)

[False  True False]


61. Find the nearest value from a given value in an array

In [15]:
arr = np.random.randint(0, 100, 10)
value = 42
nearest = arr[np.abs(arr - value).argmin()]
print(arr)
print("Nearest value to", value, ":", nearest)

[33 84 51  8 60 19 94  8 75 51]
Nearest value to 42 : 33


62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator?

In [16]:
A = np.arange(3).reshape(1, 3)
B = np.arange(3).reshape(3, 1)

it = np.nditer([A, B, None])
for x, y, z in it:
    z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


63. Create an array class that has a name attribute

In [17]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="No Name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj

arr = NamedArray(np.arange(10), "My Array")
print(arr.name)

My Array


64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [18]:
Z = np.zeros(10)
indices = np.random.randint(0, 10, 20)
np.add.at(Z, indices, 1)
print(Z)

[1. 4. 2. 0. 2. 2. 3. 3. 1. 2.]


65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)?

In [20]:
X = np.array([1, 2, 3, 4, 5])
I = np.array([0, 1, 2, 1, 3])
F = np.zeros(5)
np.add.at(F, I, X)
print(F)


[1. 6. 3. 5. 0.]


66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors

In [21]:

w, h = 5, 5
image = np.random.randint(0, 256, (w, h, 3), dtype=np.uint8)
colors = np.unique(image.reshape(-1, 3), axis=0)
print(len(colors))

25


67. Considering a four-dimensional array, how to get the sum over the last two axes at once?

In [22]:
A = np.random.rand(3, 4, 5, 6)
sum_A = A.sum(axis=(-2, -1))
print(sum_A.shape)

(3, 4)


68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset indices?

In [24]:

D = np.random.rand(10)
S = np.random.randint(0, 3, 10)
mean_values = np.bincount(S, weights=D) / np.bincount(S)
print(mean_values)

[0.39494622 0.63955427 0.10070426]


69. How to get the diagonal of a dot product?

In [25]:
A = np.random.rand(5, 5)
B = np.random.rand(5, 5)
diagonal = np.einsum("ii", np.dot(A, B))
print(diagonal)

7.256113588284609


70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?

In [26]:
Z = np.array([1, 2, 3, 4, 5])
new_Z = np.zeros(len(Z) + (len(Z) - 1) * 3)
new_Z[::4] = Z
print(new_Z)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)?

In [27]:
A = np.random.rand(5, 5, 3)
B = np.random.rand(5, 5)
result = A * B[:, :, None]
print(result)


[[[2.80265180e-01 1.52586741e-01 6.10359626e-02]
  [8.29024868e-02 3.74947846e-01 2.72758250e-01]
  [7.61388975e-02 8.64190882e-01 7.01244862e-01]
  [1.13765407e-01 4.63671685e-01 7.50235709e-01]
  [1.34231286e-01 9.75012300e-02 4.38865063e-02]]

 [[2.79516636e-01 5.58306562e-01 8.02315404e-01]
  [5.12510483e-01 5.36319443e-01 7.73098676e-01]
  [4.52369704e-01 1.07340502e-01 8.60924695e-01]
  [3.10165322e-03 2.82833348e-04 5.90909043e-04]
  [6.57121829e-01 9.84521854e-02 4.51345478e-01]]

 [[3.59288227e-01 2.77421340e-01 3.25670149e-01]
  [3.64087878e-01 5.37698181e-01 3.69940466e-01]
  [5.43278772e-02 4.51488434e-02 2.25459517e-02]
  [3.70908656e-01 7.59687353e-01 2.43075228e-01]
  [6.69676333e-02 6.39292432e-02 1.17414079e-01]]

 [[1.13345682e-01 4.08993813e-01 2.95135570e-01]
  [2.55818498e-01 5.63152701e-02 1.14364197e-01]
  [3.15764254e-02 4.57450158e-02 3.19822795e-02]
  [3.52555357e-02 8.18793796e-02 4.43399319e-02]
  [3.82887510e-01 3.80002517e-02 1.69864799e-01]]

 [[3.3594233

72. How to swap two rows of an array?

In [28]:
A = np.arange(25).reshape(5, 5)
A[[0, 1]] = A[[1, 0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C?

In [30]:
C = np.array([4, 2, 1, 3])
A = np.repeat(np.arange(len(C)), C)
print(A)

[0 0 0 0 1 1 2 3 3 3]


75. How to compute averages using a sliding window over an array?

In [31]:
def moving_average(a, n=3):
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n

arr = np.arange(10)
print(moving_average(arr, n=3))

[1. 2. 3. 4. 5. 6. 7. 8.]


76. Consider a one-dimensional array Z, build a two-dimensional array where each row is shifted by 1.

In [32]:
Z = np.arange(1, 15)
R = np.lib.stride_tricks.sliding_window_view(Z, (4,))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


77. How to negate a boolean, or change the sign of a float in place?

In [33]:
Z = np.random.randint(0, 2, 10, dtype=bool)
Z = ~Z
print(Z)

A = np.random.rand(10) * 10
A = -A
print(A)

[ True  True False  True  True  True False  True  True False]
[-0.06023373 -6.23182919 -9.41280326 -5.80686533 -4.91308975 -6.27036801
 -8.21629154 -0.87623035 -5.68033922 -8.49210465]


78. Compute distance from a point to each line defined by two points (2D case).

In [34]:
P0 = np.random.rand(5, 2)
P1 = np.random.rand(5, 2)
p = np.random.rand(1, 2)

d = np.abs(np.cross(P1 - P0, P0 - p)) / np.linalg.norm(P1 - P0, axis=1)
print(d)

[0.10818363 0.14685343 0.20662438 0.18580809 0.36407665]


C:\Users\Indira\AppData\Local\Temp\ipykernel_17552\3951450405.py:5: DeprecationWarning: Arrays of 2-dimensional vectors are deprecated. Use arrays of 3-dimensional vectors instead. (deprecated in NumPy 2.0)
  d = np.abs(np.cross(P1 - P0, P0 - p)) / np.linalg.norm(P1 - P0, axis=1)


80. Extract a subpart with a fixed shape centered on a given element (pad if necessary).

In [36]:

def extract_subarray(arr, center, shape, fill_value=0):
    R, C = arr.shape
    r, c = center
    sh_r, sh_c = shape
    
    pad = np.full((R + sh_r, C + sh_c), fill_value)
    pad[sh_r//2:R+sh_r//2, sh_c//2:C+sh_c//2] = arr
    
    return pad[r:r+sh_r, c:c+sh_c]

A = np.arange(100).reshape(10, 10)
center = (5, 5)
shape = (3, 3)
print(extract_subarray(A, center, shape))

[[44 45 46]
 [54 55 56]
 [64 65 66]]


81. Generate an array where each row is a sliding window over a given array.

In [37]:
Z = np.arange(1, 15)
R = np.lib.stride_tricks.sliding_window_view(Z, window_shape=4)
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


82. Compute the rank of a matrix.

In [38]:
A = np.random.rand(5, 5)
rank = np.linalg.matrix_rank(A)
print(rank)

5


83. Find the most frequent value in an array.

In [39]:
Z = np.random.randint(0, 10, 100)
most_frequent = np.bincount(Z).argmax()
print(most_frequent)

7


84. Extract all contiguous 3×3 blocks from a random 10×10 matrix.

In [40]:
Z = np.random.randint(0, 10, (10, 10))
blocks = np.lib.stride_tricks.sliding_window_view(Z, (3, 3))
print(blocks)

[[[[2 3 5]
   [4 5 3]
   [3 0 9]]

  [[3 5 6]
   [5 3 7]
   [0 9 5]]

  [[5 6 9]
   [3 7 9]
   [9 5 6]]

  [[6 9 7]
   [7 9 2]
   [5 6 9]]

  [[9 7 1]
   [9 2 2]
   [6 9 2]]

  [[7 1 8]
   [2 2 3]
   [9 2 0]]

  [[1 8 3]
   [2 3 4]
   [2 0 5]]

  [[8 3 8]
   [3 4 9]
   [0 5 8]]]


 [[[4 5 3]
   [3 0 9]
   [3 0 2]]

  [[5 3 7]
   [0 9 5]
   [0 2 9]]

  [[3 7 9]
   [9 5 6]
   [2 9 0]]

  [[7 9 2]
   [5 6 9]
   [9 0 8]]

  [[9 2 2]
   [6 9 2]
   [0 8 1]]

  [[2 2 3]
   [9 2 0]
   [8 1 4]]

  [[2 3 4]
   [2 0 5]
   [1 4 1]]

  [[3 4 9]
   [0 5 8]
   [4 1 5]]]


 [[[3 0 9]
   [3 0 2]
   [2 2 7]]

  [[0 9 5]
   [0 2 9]
   [2 7 2]]

  [[9 5 6]
   [2 9 0]
   [7 2 3]]

  [[5 6 9]
   [9 0 8]
   [2 3 2]]

  [[6 9 2]
   [0 8 1]
   [3 2 7]]

  [[9 2 0]
   [8 1 4]
   [2 7 6]]

  [[2 0 5]
   [1 4 1]
   [7 6 3]]

  [[0 5 8]
   [4 1 5]
   [6 3 1]]]


 [[[3 0 2]
   [2 2 7]
   [8 4 2]]

  [[0 2 9]
   [2 7 2]
   [4 2 9]]

  [[2 9 0]
   [7 2 3]
   [2 9 0]]

  [[9 0 8]
   [2 3 2]
   [9 0 1]]

  [[0 8 1]
   

85. Create a 2D array subclass where Z[i, j] == Z[j, i].

In [41]:
class SymmetricArray(np.ndarray):
    def __setitem__(self, index, value):
        i, j = index
        super(SymmetricArray, self).__setitem__((i, j), value)
        super(SymmetricArray, self).__setitem__((j, i), value)

Z = np.zeros((5, 5)).view(SymmetricArray)
Z[2, 3] = 10
print(Z)

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0. 10.  0.]
 [ 0.  0. 10.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


86. Compute the sum of p matrix products at once (p matrices of shape (n,n) and p vectors of shape (n,1)).

In [42]:
p, n = 3, 4
matrices = np.random.rand(p, n, n)
vectors = np.random.rand(p, n, 1)

result = np.einsum('ijk,ikl->ijl', matrices, vectors)
print(result)

[[[0.91791635]
  [0.72076379]
  [0.74248883]
  [1.3978555 ]]

 [[1.0963191 ]
  [1.51076057]
  [2.13090787]
  [1.74763653]]

 [[1.10647809]
  [1.49088003]
  [1.64395379]
  [1.65533064]]]


87. Compute the block sum of a 16×16 array with block size 4×4.

In [43]:
Z = np.random.rand(16, 16)
block_size = (4, 4)
block_sum = Z.reshape(4, 4, 4, 4).sum(axis=(2, 3))
print(block_sum)

[[7.27622449 8.47843502 9.55890344 7.27724196]
 [8.88912146 6.77753587 8.09457946 8.28845617]
 [9.56831337 8.28785166 9.23258358 8.29596337]
 [7.58169581 5.93080095 7.77096035 5.75956873]]


89. Find the n largest values of an array.

In [44]:
Z = np.random.randint(0, 100, 10)
n = 3
largest = np.sort(Z)[-n:]
print(largest)


[65 74 84]


90. Compute the Cartesian product of multiple arrays.

In [45]:
arrays = [np.array([1, 2, 3]), np.array([4, 5]), np.array([6, 7])]
cartesian_product = np.array(np.meshgrid(*arrays)).T.reshape(-1, len(arrays))
print(cartesian_product)

[[1 4 6]
 [1 5 6]
 [2 4 6]
 [2 5 6]
 [3 4 6]
 [3 5 6]
 [1 4 7]
 [1 5 7]
 [2 4 7]
 [2 5 7]
 [3 4 7]
 [3 5 7]]


91. Create a record array from a regular array.

In [46]:
Z = np.array([(1, 2.0, 'Hello'), (2, 3.5, 'World')], dtype=[('id', int), ('value', float), ('text', 'U10')])
print(Z)


[(1, 2. , 'Hello') (2, 3.5, 'World')]


92. Compute Z to the power of 3 using three different methods.

In [48]:
Z = np.arange(5)

power1 = Z**3
power2 = np.power(Z, 3)
power3 = np.einsum('i,i,i->i', Z, Z, Z)

print(power1, power2, power3)

[ 0  1  8 27 64] [ 0  1  8 27 64] [ 0  1  8 27 64]


94. Extract rows with unequal values from a 10×3 matrix.

In [51]:
Z = np.random.randint(0, 5, (10, 3))
unique_rows = Z[(Z[:, 0] != Z[:, 1]) | (Z[:, 1] != Z[:, 2])]
print(unique_rows)

[[0 1 4]
 [1 4 1]
 [4 1 2]
 [2 4 4]
 [1 4 3]
 [4 3 0]
 [4 0 1]
 [4 0 4]
 [0 0 2]]


95. Convert a vector of ints into a matrix binary representation.

In [52]:
Z = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
binary_matrix = ((Z[:, None] & (1 << np.arange(8))) > 0).astype(int)
print(binary_matrix)

[[0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [1 0 1 0 0 0 0 0]
 [0 1 1 0 0 0 0 0]
 [1 1 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]]


96. Extract unique rows from a 2D array.

In [53]:
Z = np.random.randint(0, 5, (10, 3))
unique_rows = np.unique(Z, axis=0)
print(unique_rows)

[[0 1 1]
 [0 1 4]
 [1 0 3]
 [1 1 2]
 [2 4 0]
 [3 0 1]
 [3 2 2]
 [3 3 3]
 [4 1 3]
 [4 2 1]]


97. Compute einsum equivalents for inner, outer, sum, and multiplication.

In [54]:
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

inner = np.einsum('i,i->', A, B) 
outer = np.einsum('i,j->ij', A, B)
sum_all = np.einsum('i->', A)  
mul = np.einsum('i,i->i', A, B) 

print(inner, "\n", outer, "\n", sum_all, "\n", mul)

32 
 [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]] 
 6 
 [ 4 10 18]


98. Sample a path using equidistant samples.

In [55]:
X = np.linspace(0, 10, num=100)
Y = np.sin(X)
sample_points = np.linspace(0, 10, num=10)
sampled_Y = np.interp(sample_points, X, Y)
print(sampled_Y)

[ 0.          0.8961922   0.79522006 -0.19056796 -0.96431712 -0.66510151
  0.37415123  0.99709789  0.51060568 -0.54402111]


99. Select rows that can be interpreted as draws from a multinomial distribution.

In [56]:
X = np.array([[1, 2, 2], [3, 3, 3], [2, 2, 2], [1, 1, 3]])
n = 5
valid_rows = X[np.all(X.sum(axis=1) == n, axis=0)]
print(valid_rows)

[]


100. Compute bootstrapped 95% confidence intervals for the mean of an array.

In [57]:
X = np.random.randn(1000)
N = 1000  # Number of resamples
means = np.random.choice(X, (N, len(X)), replace=True).mean(axis=1)
ci_lower, ci_upper = np.percentile(means, [2.5, 97.5])

print(f"95% Confidence Interval: ({ci_lower}, {ci_upper})")

95% Confidence Interval: (-0.10307247362116541, 0.016713178873121307)


# Homework 2

In [58]:
arr = np.arange(1, 11)

squared_arr = arr ** 2
sum_squared = np.sum(squared_arr)
mean_squared = np.mean(squared_arr)
std_squared = np.std(squared_arr)

print("array:", arr)
print("Square:", squared_arr)
print("sum:", sum_squared)
print("mean:", mean_squared)
print("standart deviation:", std_squared)


array: [ 1  2  3  4  5  6  7  8  9 10]
Square: [  1   4   9  16  25  36  49  64  81 100]
sum: 385
mean: 38.5
standart deviation: 32.41990129534635
